name: roc_date_time
version: 1.0.0
description: A Dart package providing custom DateTime classes for displaying dates in the Republic of China (ROC) calendar.
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
