name: roc_date_time
version: 1.0.0
description: A Dart package providing custom DateTime classes for displaying dates in the Republic of China (ROC) calendar.
homepage: https://globetrotter-studio.com
repository: https://github.com/ShiKai-Pan/roc_date_time
issue_tracker: https://github.com/ShiKai-Pan/roc_date_time/issues
environment:
  sdk: ^3.1.5
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
